"""Generates the harmless Python snippet that the demo types remotely.

Constraints that keep the generated text survivable when typed into an editor:

* no tab characters -- indentation is spaces only
* no backslashes, so nothing depends on escape handling
* every line's brackets and quotes are balanced, so an editor's auto-closing
  never leaves a stray character behind
* no triple-quoted strings -- a third consecutive quote is where auto-closing
  stops behaving predictably, so comments are used instead of docstrings
* nothing touches the filesystem, network, or environment when it runs
"""

from __future__ import annotations

import random
from datetime import datetime

FUNCTIONS: list[tuple[str, list[str]]] = [
    ("total", [
        "def total(values):",
        '    # Add up a list of numbers.',
        "    result = 0",
        "    for value in values:",
        "        result = result + value",
        "    return result",
    ]),
    ("mean", [
        "def mean(values):",
        '    # Average of a list, or 0.0 when it is empty.',
        "    if not values:",
        "        return 0.0",
        "    return sum(values) / len(values)",
    ]),
    ("evens", [
        "def evens(values):",
        '    # Keep only the even numbers.',
        "    return [value for value in values if value % 2 == 0]",
    ]),
    ("squares", [
        "def squares(limit):",
        '    # Squares of 0 up to limit, exclusive.',
        "    return [n * n for n in range(limit)]",
    ]),
    ("countdown", [
        "def countdown(start):",
        '    # Count down to 1 and collect the steps.',
        "    steps = []",
        "    while start > 0:",
        "        steps.append(start)",
        "        start = start - 1",
        "    return steps",
    ]),
    ("longest", [
        "def longest(words):",
        '    # Return the longest word, or an empty string.',
        "    best = ''",
        "    for word in words:",
        "        if len(word) > len(best):",
        "            best = word",
        "    return best",
    ]),
    ("fizz", [
        "def fizz(n):",
        '    # Classic small branching exercise.',
        "    if n % 15 == 0:",
        "        return 'fizzbuzz'",
        "    if n % 3 == 0:",
        "        return 'fizz'",
        "    if n % 5 == 0:",
        "        return 'buzz'",
        "    return str(n)",
    ]),
]

WORDS = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf",
         "hotel", "india", "juliett", "kilo", "lima"]

# How each function is exercised in the __main__ block.
CALLS = {
    "total": "print('total     ', total(NUMBERS))",
    "mean": "print('mean      ', round(mean(NUMBERS), 3))",
    "evens": "print('evens     ', evens(NUMBERS))",
    "squares": "print('squares   ', squares(6))",
    "countdown": "print('countdown ', countdown(5))",
    "longest": "print('longest   ', longest(WORDS))",
    "fizz": "print('fizz      ', [fizz(n) for n in range(1, 16)])",
}


def generate(seed: int | None = None, how_many: int = 3) -> str:
    """Build a small, self-contained Python module as a string.

    Passing the same ``seed`` reproduces the same module, which makes a failed
    demo run easy to repeat.
    """
    rng = random.Random(seed)
    how_many = max(1, min(how_many, len(FUNCTIONS)))
    chosen = rng.sample(FUNCTIONS, how_many)

    numbers = [rng.randint(1, 40) for _ in range(rng.randint(5, 8))]
    words = rng.sample(WORDS, rng.randint(3, 5))
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = [
        "# Generated by rdp-background-automation.",
        f"# Typed into this editor over RDP on {stamp}.",
        f"# Seed: {seed if seed is not None else 'random'}",
        "",
        f"NUMBERS = {numbers}",
        f"WORDS = {words}",
        "",
        "",
    ]

    for name, body in chosen:
        lines.extend(body)
        lines.extend(["", ""])

    lines.append("if __name__ == '__main__':")
    lines.append("    print('automation demo starting')")
    for name, _ in chosen:
        lines.append("    " + CALLS[name])
    lines.append("    print('automation demo done')")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(
        "rdpauto/code_generator.py is part of the application, not an entry point. "
        "Start it with:  python gui.py   (desktop)  or  python cli.py   (server)"
    )
